create table if not exists public.pre_signups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  telegram_user_id bigint not null unique,
  telegram_username text,
  name text not null,
  email text not null,
  referral_code text not null unique,
  referred_by text,
  age_confirmed boolean not null default false
);

create index if not exists pre_signups_email_idx
  on public.pre_signups (lower(email));

create index if not exists pre_signups_referred_by_idx
  on public.pre_signups (referred_by);

alter table public.pre_signups enable row level security;

-- The bot uses the Supabase service-role key server-side.
-- Never expose that key in a browser or client application.
